### ISSUE TITLE
Headers sometimes got sorted with items when add items repeatedly

### ISSUE THREAD

**Issue by hubertwang** [brewster/SMGridView#2]
Hi, 

I am recently using SMGridView in my project. I found that when I add items fast and continuously, sometimes header of the target section will be obtained by using dequeueReusableVIew. So it will looks like the header view move down and sort with the items in section. 

Anyone got the same problem before? I am wondering if I was using it in a wrong way. 

Hubert

**Comment by mcohnen** [comment]
Hi,

You can use - (UIView *)dequeReusableViewOfClass:(Class)clazz; to only get views that are from a specific class. Simply have your header and your cells be Views from different classes, and pass your cell view class to this method to only get cell items. 

Let me know if it works!

**Comment by hubertwang** [comment]
Hi, 

I reviewed my codes and tried - (UIView *)dequeReusableViewOfClass:(Class)clazz. Unfortunately, it did not works.
I found that the problem is not from dequeueReusableView. I replaced them with dequeReusableViewOfClass but the header views still move down. 

I just recalled that this problem did happen in the demo project, too. I took a snapshot below: 
![2013-06-03 9 50 55](https://f.cloud.github.com/assets/1281311/597339/a33e1ef0-cbf0-11e2-83a4-addbb6c90f6c.png)
It can be seen that section 0 is in the left midd part of the items.

**Comment by hubertwang** [comment]
Oh, forgot to say, In the case, I clicks + button continuously and it happens.

**Comment by mcohnen** [comment]
Oh, so it might be an issue with repeatedly adding items to the GridView. I'll have a look at this. 
I assume you found this issue when normally dealing with the GridView, or only when pressing + button repeated times?

**Comment by mcohnen** [comment]
There seems to be something broken with adding items due to some late commits. I'll fix it and let you know in this thread whenever it is ready.

**Comment by mcohnen** [comment]
I pushed a fix for a bug adding items. I'm not 100% sure this will fix the header issue when pressing + button repeatdly, but definitely there was an issue when adding items using animation.

Pull the latest from master and let me  now if it works better

**Comment by hubertwang** [comment]
Thanks! I'll test it later. By the way, will u update a new version on cocoa pods?

**Comment by hubertwang** [comment]
![img_0159](https://f.cloud.github.com/assets/1281311/719754/a323a64c-df96-11e2-87c8-54b1a2e80066.png)
Seems that it's still happening..
